### DISCUSSION TITLE
我觉得可以把上报类型的消息改改捏

### DISCUSSION THREAD

**Discussion by xianyubb** [Mrs4s/go-cqhttp#2357] [Ideas]
当前的上报类型分为两种：
一种是 string 一种是 array 这两者的差别就在于 message 不同
前者是字符串，后者是数组 而用数组的bot不太多（我知道的就go-cq版本的云崽bot在使用），用string的比较多，
其中用string的大多会直接使用message，而不是使用raw_message，
这就导致如果我要用array，就可能会失去对其他bot的支持
所以我建议如果设置成array时，将raw_message设置成数组形式，而不是message，这样大大增加了bot的通用性
或者对每一个协议作出不同的上报类型
或者直接砍掉，默认就message是string，raw_messgae是array

我知道我的想法可能有点der...

**Comment by 1umine** [comment]
没看懂，没用过string上报，设置string上报时message字段不是string吗？用string的我还没见到，不知道哪个bot框架是要求用string上报处理消息的。
gocq 是 onebot 实现，目前是 v11，消息内容格式都是参照 [onebot-v11文档](https://github.com/botuniverse/onebot-11/blob/master/event/README.md) ，其中的`raw_message`字段就是表示原始消息字符串。而`message`是根据配置选择是 string 还是 array 。
而且用处理结构化的数组消息比直接处理字符串更方便易懂，表达能力更强，可以方便地进行嵌套，规定数据类型等（参照 [onebot array message](https://github.com/botuniverse/onebot-11/blob/master/message/array.md)）。使用 gocq 的很多都是用 [nonebot](https://github.com/nonebot/nonebot2) 的，消息上报采用的也都是 array 形式。

**Reply by rhwong** [reply]
我大概能理解他的意思，有issue也提到这个了。
其实就是把go-cqhttp端接收message的可调节选项 `post-format` 从一个整体设置改为分服务设置，
比如：
```
servers:
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器

  - http: # HTTP 通信设置
      post-format: array
      address: 0.0.0.0:5700 # HTTP监听地址
      version: 11     # OneBot协议版本, 支持 11/12
      timeout: 5      # 反向 HTTP 超时时间, 单位秒，<5 时将被忽略
      long-polling:   # 长轮询拓展
        enabled: false       # 是否开启
        max-queue-size: 2000 # 消息队列大小，0 表示不限制队列大小，谨慎使用
      middlewares:
        <<: *default # 引用默认中间件
      post:           # 反向HTTP POST地址列表
      #- url: ''                # 地址
      #  secret: ''             # 密钥
      #  max-retries: 3         # 最大重试，0 时禁用
      #  retries-interval: 1500 # 重试时间，单位毫秒，0 时立即
      #- url: http://127.0.0.1:5701/ # 地址
      #  secret: ''                  # 密钥
      #  max-retries: 10             # 最大重试，0 时禁用
      #  retries-interval: 1000      # 重试时间，单位毫秒，0 时立即
  # 正向WS设置
  - ws:
      # 正向WS服务器监听地址
      post-format: string
      address: 0.0.0.0:8080
      middlewares:
        <<: *default # 引用默认中间件
  # 反向WS设置
  - ws-reverse:
      # 反向WS Universal 地址
      # 注意 设置了此项地址后下面两项将会被忽略
      post-format: array
      universal: ws://your_websocket_universal.server
      # 反向WS API 地址
      api: ws://your_websocket_api.server
      # 反向WS Event 地址
      event: ws://your_websocket_event.server
      # 重连间隔 单位毫秒
      reconnect-interval: 3000
      middlewares:
        <<: *default # 引用默认中间件
  - ws:
      # 正向WS服务器监听地址
      post-format: string
      address: 0.0.0.0:8080
      middlewares:
        <<: *default # 引用默认中间件
```
 以此达到同时对接不同上报形式的bot内容端。
