### ISSUE TITLE
Mongodb 启用无效

### ISSUE THREAD

**Issue by Kerwin1202** [Mrs4s/go-cqhttp#1158]
**环境信息**
go-cqhttp版本: v1.0.0-beta8
运行环境: win10
连接方式: http 通信
使用协议: ipad

**在最新的release版本中能否复现**
是

**bug内容**
mongodb 无法使用

**复现方法**
```
database: # 数据库相关设置
  leveldb:
    # 是否启用内置leveldb数据库
    # 启用将会增加10-20MB的内存占用和一定的磁盘空间
    # 关闭将无法使用 撤回 回复 get_msg 等上下文相关功能
    enable: false
    
  mongodb:
    enable: true
    uri: 'xxx:27017'
    database: 'cq'

  # 媒体文件缓存， 删除此项则使用缓存文件(旧版行为)
  cache:
    image: data/image.db
    video: data/video.db
```

mongodb暂时没设置密码
尝试发消息 接受消息，并没有发现创建任何数据表，日志也没有任何关于db的输出

**Comment by Ink-33** [comment]
启用mongodb需要自行编译
https://github.com/Mrs4s/go-cqhttp/blob/master/main.go#L32
需要使用mongodb就加一行
`_ "github.com/Mrs4s/go-cqhttp/db/mongodb"`

**Comment by Kerwin1202** [comment]
自己编译的支持了，可以使用，大小变为 20.6M 。如果有其他人需要所以上传了附件

配置得是
```
  mongodb:
    enable: true
    uri: 'mongodb://ip:port'
    database: 'name'
```


有个问题，如果多账号情况指向同一个 db 的，这时候数据好像是没有字段没区分的。(运行目录是分开复制的)


[go-cqhttp-mongo-amd64.zip](https://github.com/Mrs4s/go-cqhttp/files/7533356/go-cqhttp-mongo-amd64.zip)
