### ISSUE TITLE
上报请求体为空

### ISSUE THREAD

**Issue by Mother-Ship** [Mrs4s/go-cqhttp#1166]
**环境信息**

go-cqhttp版本: v1.0.0-beta8
运行环境: Ubuntu 18.04
连接方式: HTTP
使用协议: HTTP

**在最新的release版本中能否复现**
可以
**bug内容**

使用HTTP POST上报消息时，请求体为空，但开启debug后日志中有打印正确请求体
1.0.0-beta7版本使用相同配置文件，可以正常上报

**复现方法**

1.启动go-cqhttp
2.配置账号密码，以及server信息
3.编写一个简易HTTP服务器，监听该地址，从输入流中获取所有请求体并打印

server段配置如下：（#myurl'#为我的服务器地址）
```yml
servers:
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器
  # HTTP 通信设置
  - http:
      # 服务端监听地址
      host: 0.0.0.0
      # 服务端监听端口
      port: 5700
      # 反向HTTP超时时间, 单位秒
      # 最小值为5，小于5将会忽略本项设置
      timeout: 5
      # 长轮询拓展
      long-polling:
        # 是否开启
        enabled: false
        # 消息队列大小，0 表示不限制队列大小，谨慎使用
        max-queue-size: 2000
      middlewares:
        <<: *default # 引用默认中间件
      # 反向HTTP POST地址列表
      post:
       - url: '#myurl#' # 地址
      #  secret: ''           # 密钥
      #- url: 127.0.0.1:5701 # 地址
      #  secret: ''          # 密钥
```
