### ISSUE TITLE
v1.0.0-beta8-fix1的http post配置文件变更

### ISSUE THREAD

**Issue by xzsk2** [Mrs4s/go-cqhttp#1169]
**环境信息**

go-cqhttp版本: v1.0.0-beta8-fix1
运行环境: 阿里云ecs 及本地 archlinux amd64
连接方式: 反向HTTP POST
使用协议: iPad

**在最新的release版本中能否复现**

**bug内容**

**复现方法**

在v1.0.0-beta7-fix2及之前的版本中默认配置及文档里的这种写法是可以正常使用的

```
      post:
      #- url: '' # 地址
      #  secret: ''           # 密钥
      - url: 127.0.0.1:5701 # 地址
        secret: ''          # 密钥
```

beta8 之后会造成下面的报错且没有发送数据

```
[2021-11-16 14:14:25] [WARNING]: 处理事件 map[anonymous:<nil> font:0 group_id:*** message:*** message_id:771169149 message_seq:562753 message_type:group post_type:message raw_message:*** self_id:*** sender:map[age:0 area: card:*** level: nickname:*** role:member sex:unknown title:*** user_id:***] sub_type:normal time:1637043264 user_id:***] 时出现错误: runtime error: invalid memory address or nil pointer dereference 
goroutine 76 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).dispatchEventMessage.func1.1()
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:509 +0x6a
panic({0xbc8460, 0x13ef1d0})
        runtime/panic.go:1038 +0x215
github.com/Mrs4s/go-cqhttp/server.(*HTTPClient).onBotPushEvent(0xc00058f810, 0xc00051a840)
        github.com/Mrs4s/go-cqhttp/server/http.go:240 +0x2af
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).dispatchEventMessage.func1(0xc000c66900)
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:514 +0xc6
created by github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).dispatchEventMessage
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:505 +0x10f
 
[2021-11-16 14:14:27] [WARNING]: 处理事件 map[interval:5000 meta_event_type:heartbeat post_type:meta_event self_id:*** status:map[app_enabled:true app_good:true app_initialized:true good:true online:true plugins_good:<nil> stat:0xc000032d98] time:1637043267] 时出现错误: runtime error: invalid memory address or nil pointer dereference 
goroutine 163 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).dispatchEventMessage.func1.1()
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:509 +0x6a
panic({0xbc8460, 0x13ef1d0})
        runtime/panic.go:1038 +0x215
github.com/Mrs4s/go-cqhttp/server.(*HTTPClient).onBotPushEvent(0xc00058f810, 0xc0004de060)
        github.com/Mrs4s/go-cqhttp/server/http.go:240 +0x2af
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).dispatchEventMessage.func1(0xc000c66900)
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:514 +0xc6
created by github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).dispatchEventMessage
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:505 +0x10f
```

更改成 `- url: 'http://127.0.0.1:8000'` 后正常

```
      post:
      #- url: '' # 地址
      #  secret: ''           # 密钥
      - url: 'http://127.0.0.1:8000' # 地址
        secret: ''          # 密钥
```
