### ISSUE TITLE
控制台输出的反向ws universal服务器地址有误

### ISSUE THREAD

**Issue by zhanbao2000** [Mrs4s/go-cqhttp#1192]
> 很抱歉使用这个form来提交bug，我尝试过使用`回报错误`那个form尝试提交这个bug，但是每一次提交，Github都报500 Internal Server Error导致issue提交失败，我不知道是Github服务器的问题还是form的问题，所以无奈之下只能用这个form来提交了。

go-cqhttp 版本：v1.0.0-beta8-fix1
运行环境：Ubuntu amd64
连接方式：反向WebSocket
使用协议：iPad

### 重现步骤：
1、按如下配置设置反向ws，并且关闭其他连接方式
```
  - ws-reverse:
      # 是否禁用当前反向WS服务
      disabled: false
      # 反向WS Universal 地址
      # 注意 设置了此项地址后下面两项将会被忽略
      universal: ws://127.0.0.1:9492/cqhttp/ws
      # 反向WS API 地址
      api: ws://your_websocket_api.server
      # 反向WS Event 地址
      event: ws://your_websocket_event.server
      # 重连间隔 单位毫秒
      reconnect-interval: 30000
      middlewares:
        <<: *default # 引用默认中间件
```
2、启动go-cqhttp

### 期望的结果
建立连接后，控制台按照配置文件输出正确的反向ws universal连接地址，即`ws://127.0.0.1:9492/cqhttp/ws`

### 实际的结果
控制台将反向ws api地址当作反向ws universal地址输出，如下
```
[2021-11-25 02:57:30] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://your_websocket_api.server
[2021-11-25 02:57:30] [INFO]: 已连接到反向WebSocket Universal服务  ws://your_websocket_api.server
```

### 备注
 - 1.0.0-beta7-fix2版本不会出现此bug，控制台输出的是正确的反向ws universal连接地址
 - ws连接能够正常建立，应该仅仅是显示问题
