### ISSUE TITLE
希望可以添加事件上报失败后重试的次数配置

### ISSUE THREAD

**Issue by Akitora-R** [Mrs4s/go-cqhttp#1252]
**环境信息**
Debian 10.2.1-6 amd64

go-cqhttp版本: 
v1.0.0-beta8-fix2

**需要添加的功能内容**
希望可以添加事件上报失败后重试的次数配置，如
```yml
servers:
  - http:
      host: 127.0.0.1
      port: 5700
      timeout: 10
      # 重试次数
      retry-times: 10
```
