### ISSUE TITLE
[Bug]: 正向WS设置监听端口无效

### ISSUE THREAD

**Issue by ssttkkl** [Mrs4s/go-cqhttp#1600]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

配置文件中设置为正向WS，监听6700端口
```yaml
servers:
  - ws:   # 正向 Websocket
    address: 0.0.0.0:6700
    middlewares:
      <<: *default # 引用默认中间件
```

### 期望的结果是什么？

程序启动后监听6700端口

### 实际的结果是什么？

6700端口未被使用的前提下，程序启动后监听了一个随机端口

![QQ截图20220721210848](https://user-images.githubusercontent.com/17331698/180221310-129e63f2-1727-4333-9e5d-4b71c0a10491.png)
![QQ截图20220721210910](https://user-images.githubusercontent.com/17331698/180221368-3871cbf6-bd5d-4302-9dcf-dea776a551e0.png)
