### ISSUE TITLE
[Bug]: "配置文件不合法!yaml: line 96: did not find expected key

### ISSUE THREAD

**Issue by jellyqwq** [Mrs4s/go-cqhttp#1681]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

生成配置时选择0 http, 然后把 ` address: 0.0.0.0:5700 # HTTP监听地址` 这行注释掉, 配置反向http

```
# 连接服务列表
servers:
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器

  - http: # HTTP 通信设置
      #address: 0.0.0.0:5700 # HTTP监听地址
      timeout: 5      # 反向 HTTP 超时时间, 单位秒，<5 时将被忽略
      long-polling:   # 长轮询拓展
        enabled: false       # 是否开启
        max-queue-size: 2000 # 消息队列大小，0 表示不限制队列大小，谨慎使用
      middlewares:
        <<: *default # 引用默认中间件
      post:           # 反向HTTP POST地址列表
       - url: 'http://127.0.0.1:5701/'                # 地址
        secret: ''             # 密钥
        max-retries: 3         # 最大重试，0 时禁用
        retries-interval: 1500 # 重试时间，单位毫秒，0 时立即
      #- url: http://127.0.0.1:5701/ # 地址
      #  secret: ''                  # 密钥
      #  max-retries: 10             # 最大重试，0 时禁用
      #  retries-interval: 1000      # 重试时间，单位毫秒，0 时立即
```

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

```
time="2022-09-10T17:49:55+08:00" level=fatal msg="配置文件不合法!yaml: line 96: did not find expected key"
```
line 96就是上述的`address`行

### 解决办法

如果把address注释掉, 启用反向http, 则需要把`- http: # HTTP 通信设置`下的配置前减少两个空格

```
# 连接服务列表
servers:
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器

  - http: # HTTP 通信设置
    #address: 0.0.0.0:5700 # HTTP监听地址
    timeout: 5      # 反向 HTTP 超时时间, 单位秒，<5 时将被忽略
    long-polling:   # 长轮询拓展
      enabled: false       # 是否开启
      max-queue-size: 2000 # 消息队列大小，0 表示不限制队列大小，谨慎使用
    middlewares:
      <<: *default # 引用默认中间件
    post:           # 反向HTTP POST地址列表
     - url: 'http://127.0.0.1:5701/'                # 地址
      secret: ''             # 密钥
      max-retries: 3         # 最大重试，0 时禁用
      retries-interval: 1500 # 重试时间，单位毫秒，0 时立即
    #- url: http://127.0.0.1:5701/ # 地址
    #  secret: ''                  # 密钥
    #  max-retries: 10             # 最大重试，0 时禁用
    #  retries-interval: 1000      # 重试时间，单位毫秒，0 时立即
```
