### ISSUE TITLE
[Bug]: sqlite3似乎不能正常单独开启

### ISSUE THREAD

**Issue by OREOCODEDEV** [Mrs4s/go-cqhttp#2005]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0-rc5

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

WebSocket (反向)

### 使用协议

1 | Android Phone

### 重现步骤

***使用的协议实际为 6(aPad) ，issue模板里面没有这个协议只能随便选一个**

**复现步骤：**
1.配置项中关闭leveldb，并打开sqlite3
```
database: # 数据库相关设置
  leveldb:
    # 是否启用内置leveldb数据库
    # 启用将会增加10-20MB的内存占用和一定的磁盘空间
    # 关闭将无法使用 撤回 回复 get_msg 等上下文相关功能
    enable: false
  sqlite3:
    # 是否启用内置sqlite3数据库
    # 启用将会增加一定的内存占用和一定的磁盘空间
    # 关闭将无法使用 撤回 回复 get_msg 等上下文相关功能
    enable: true
    cachettl: 3600000000000 # 1h
```
2.使用 `get_meg` API获取任意消息
3.控制台提示 `[WARNING]: 获取消息时出现错误: database disabled`

### 期望的结果是什么？

leveldb 和 sqlite3 应该是任意一个打开都应该可以正常使用 gocq 数据库相关功能的？还是我对配置项的理解有误会（

### 实际的结果是什么？

leveldb 和 sqlite3 应该是任意一个打开都可以正常使用 gocq 数据库相关功能的，实际在单独打开 sqlite3 后使用 `get_msg` API提示数据库已禁用
