### ISSUE TITLE
[Bug]: v1.0.1 上报Event数据 post失败 with 'context deadline exceeded' 

### ISSUE THREAD

**Issue by Hanabi1688** [Mrs4s/go-cqhttp#2288]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [x] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.1

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

qq用，windows本地部署成功，且消息正常post到端口，能正常使用。于是把项目部署到云服务器，出现上报Event数据 post失败 with 'context deadline exceeded'
![1](https://github.com/Mrs4s/go-cqhttp/assets/54924778/cc11b197-9bf5-47b9-84e4-c0d69ca87ac0)

### 期望的结果是什么？

能成功post

### 实际的结果是什么？

post失败 'context deadline exceeded'

### 简单的复现代码/链接（可选）

```golang
wget https://github.com/Mrs4s/go-cqhttp/releases/download/v1.0.1/go-cqhttp_1.0.1_linux_amd64.deb
sudo apt-get install dpkg
sudo dpkg -i go-cqhttp_1.0.1_linux_amd64.deb
go-cqhttp
```

### 补充说明（可选）

没找到原因，因此我已经尝试过重装系统，使用虚拟环境等步骤，但无法解决。如果大佬们能分享对这个issue的专业见解,我将不胜感激。

**Comment by xiarimangguo** [comment]
请打开go-cqhttp的config.yml  
找到-server  
设置timeout为更大的数值  

```
servers:
    - http: # HTTP 通信设置
      address: 127.0.0.1:8000 # HTTP监听地址
      timeout: 5      # 反向 HTTP 超时时间, 单位秒，<5 时将被忽略
      long-polling:   # 长轮询拓展
        enabled: false       # 是否开启
        max-queue-size: 2000 # 消息队列大小，0 表示不限制队列大小，谨慎使用
      middlewares:
        <<: *default # 引用默认中间件
      post:           # 反向HTTP POST地址列表
  # 正向WS设置
  - ws:
      # 正向WS服务器监听地址
      address: 127.0.0.1:5700
      middlewares:
        <<: *default # 引用默认中间件
```
