### ISSUE TITLE
[Bug]: 在docker-compose使用中貌似有问题

### ISSUE THREAD

**Issue by Admmmmmmin** [Mrs4s/go-cqhttp#2376]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

docker的最新一次版本

### 运行环境

CentOS

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | Default

### 重现步骤

*使用 [ls233](https://github.com/lss233/chatgpt-mirai-qq-bot) 的 docker-compose [脚本](https://github.com/lss233/chatgpt-mirai-qq-bot#:~:text=Linux%3A%20%E9%80%9A%E8%BF%87%E5%BF%AB%E9%80%9F%E9%83%A8%E7%BD%B2%E8%84%9A%E6%9C%AC%E9%83%A8%E7%BD%B2%20%EF%BC%88%E6%96%B0%E4%BA%BA%E6%8E%A8%E8%8D%90) 部署。*

相关代码如下：
```yml
# docker-compose 文档
  gocqhttp:
    image: silicer/go-cqhttp:latest
    restart: always
    environment:
      LANG: 'C.UTF-8'
    ports:
      - "8848:8848"
    volumes:
      - ./gocqhttp/:/data/
```
```yml
# config.yml 文档
# 连接服务列表
servers:
  - ws-reverse:
      universal: ws://chatgpt:8554/ws
  - http: # HTTP 通信设置
    address: 0.0.0.0:8848 # HTTP监听地址
    version: 11     # OneBot协议版本, 支持 11/12
    timeout: 5      # 反向 HTTP 超时时间, 单位秒，<5 时将被忽略
    long-polling:   # 长轮询拓展
      enabled: false       # 是否开启
      max-queue-size: 2000 # 消息队列大小，0 表示不限制队列大小，谨慎使用
    middlewares:
      <<: *default # 引用默认中间件
    post:           # 反向HTTP POST地址列表
```
配合前述机器人使用没有问题。

### 期望的结果是什么？

可以正确执行 curl 命令

### 实际的结果是什么？

在打开正向 HTTP 服务器并在 docker 放行相关端口之后，从容器外 curl 没有结果，提示 `curl: (52) Empty reply from server`，打开debug 模式后继续 curl 也没有相关输出，但是 QQ 消息的发送接受完全正常。

命令 `docker ps` 后的结果：
```zsh
CONTAINER ID   IMAGE                                         COMMAND                  CREATED       STATUS       PORTS                                       NAMES
**             silicer/go-cqhttp:latest                      "/usr/bin/cqhttp"        5 hours ago   Up 2 hours   0.0.0.0:8848->8848/tcp, :::8848->8848/tcp   chatgpt-qq-gocqhttp-1
```
执行命令试图进入容器：
```zsh
➜  ~ docker exec -it ** /usr/bin/cqhttp
[2023-08-15 05:41:38] [FATAL]: open cache image db failed: resource temporarily unavailable 
```
docker 的状态：
```
➜  ~ systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Mon 2023-08-14 17:44:40 UTC; 3h 58min ago
     Docs: https://docs.docker.com
 Main PID: 1355 (dockerd)
    Tasks: 46
   Memory: 126.7M
   CGroup: /system.slice/docker.service
           ├─ ***
           ├─16474 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8848 -container-ip *.*.*.3 -container-port 8848
           └─16485 /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 8848 -container-ip *.*.*.3 -container-port 8848
```

同 compose 中的其他容器均可以通过 exec 进入容器内部。

### 补充说明（可选）

* 未使用 dev 分支测试过
